# Generated by Django 4.1.7 on 2023-06-27 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0083_workflowcontenttype"),
        ("spstaglib", "0004_spselement_attributes_attributevalue"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="spsbase",
            name="created",
        ),
        migrations.RemoveField(
            model_name="spsbase",
            name="creator",
        ),
        migrations.RemoveField(
            model_name="spsbase",
            name="id",
        ),
        migrations.RemoveField(
            model_name="spsbase",
            name="updated",
        ),
        migrations.RemoveField(
            model_name="spsbase",
            name="updated_by",
        ),
        migrations.AddField(
            model_name="spsbase",
            name="page_ptr",
            field=models.OneToOneField(
                auto_created=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="wagtailcore.page",
            ),
            preserve_default=False,
        ),
    ]
